/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 11-jun.-2021 19:10:25 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_cliente_persona]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [cliente] DROP CONSTRAINT [FK_cliente_persona]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_id_orden]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [detalle_orden] DROP CONSTRAINT [FK_id_orden]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_id_producto]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [detalle_orden] DROP CONSTRAINT [FK_id_producto]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_orden_venta_cliente]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [orden_venta] DROP CONSTRAINT [FK_orden_venta_cliente]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_orden_venta_metodo_pago]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [orden_venta] DROP CONSTRAINT [FK_orden_venta_metodo_pago]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_orden_venta_orden]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [orden_venta] DROP CONSTRAINT [FK_orden_venta_orden]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_producto_categoria]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [producto] DROP CONSTRAINT [FK_producto_categoria]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_tarjeta_orden_venta]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [tarjeta] DROP CONSTRAINT [FK_tarjeta_orden_venta]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_usuario_persona]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [usuario] DROP CONSTRAINT [FK_usuario_persona]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_usuario_rol]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [usuario] DROP CONSTRAINT [FK_usuario_rol]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[categoria]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [categoria]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[cliente]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [cliente]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[detalle_orden]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [detalle_orden]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[direccion]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [direccion]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[metodo_pago]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [metodo_pago]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[orden]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [orden]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[orden_venta]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [orden_venta]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[persona]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [persona]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[producto]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [producto]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[rol]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [rol]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[tarjeta]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [tarjeta]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[usuario]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [usuario]
GO

/* Create Tables */

CREATE TABLE [categoria]
(
	[id_categoria] int NOT NULL IDENTITY (1, 1),
	[nombre] varchar(50) NOT NULL
)
GO

CREATE TABLE [cliente]
(
	[id_persona] int NOT NULL
)
GO

CREATE TABLE [detalle_orden]
(
	[id_detalle_orden] int NOT NULL IDENTITY (1, 1),
	[cantidad] varchar(50) NOT NULL,
	[id_orden] int NOT NULL,
	[id_producto] int NOT NULL
)
GO

CREATE TABLE [direccion]
(
	[id_direccion] int NOT NULL IDENTITY (1, 1),
	[altura] varchar(50) NOT NULL,
	[calle] varchar(50) NOT NULL,
	[codigo_postal] varchar(50) NOT NULL,
	[localidad] varchar(50) NOT NULL,
	[provincia] varchar(50) NOT NULL
)
GO

CREATE TABLE [metodo_pago]
(
	[id_metodo_pago] int NOT NULL IDENTITY (1, 1),
	[descripcion] varchar(50) NOT NULL
)
GO

CREATE TABLE [orden]
(
	[id_orden] int NOT NULL IDENTITY (1, 1),
	[fecha] datetime NOT NULL,
	[id_usuario_creador] int NULL
)
GO

CREATE TABLE [orden_venta]
(
	[id_metodo_pago] int NOT NULL,
	[id_cliente] int NULL,
	[id_orden] int NOT NULL
)
GO

CREATE TABLE [persona]
(
	[id_persona] int NOT NULL IDENTITY (1, 1),
	[apellido] varchar(50) NOT NULL,
	[dni] varchar(50) NOT NULL,
	[nombre] varchar(50) NOT NULL,
	[id_direccion] int NOT NULL
)
GO

CREATE TABLE [producto]
(
	[id_producto] int NOT NULL IDENTITY (1, 1),
	[nombre] varchar(50) NOT NULL,
	[precio_compra] float NOT NULL,
	[precio_venta] float NOT NULL,
	[id_categoria] int NOT NULL,
	[stock] int NOT NULL
)
GO

CREATE TABLE [rol]
(
	[id_rol] int NOT NULL IDENTITY (1, 1),
	[descripcion] varchar(50) NOT NULL
)
GO

CREATE TABLE [tarjeta]
(
	[id_tarjeta] int NOT NULL IDENTITY (1, 1),
	[cvc] varchar(50) NOT NULL,
	[fecha_vencimiento] varchar(50) NOT NULL,
	[nombre_tarjeta] varchar(50) NOT NULL,
	[numero_tarjeta] int NOT NULL,
	[id_orden] int NOT NULL
)
GO

CREATE TABLE [usuario]
(
	[id_persona] int NOT NULL,
	[id_rol] int NOT NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [categoria] 
 ADD CONSTRAINT [PK_categoria]
	PRIMARY KEY CLUSTERED ([id_categoria] ASC)
GO

ALTER TABLE [cliente] 
 ADD CONSTRAINT [PK_cliente]
	PRIMARY KEY CLUSTERED ([id_persona] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_cliente_persona] 
 ON [cliente] ([id_persona] ASC)
GO

ALTER TABLE [detalle_orden] 
 ADD CONSTRAINT [PK_id_detalle_orden]
	PRIMARY KEY CLUSTERED ([id_detalle_orden] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_id_producto] 
 ON [detalle_orden] ([id_producto] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_id_orden] 
 ON [detalle_orden] ()
GO

ALTER TABLE [direccion] 
 ADD CONSTRAINT [PK_direccion]
	PRIMARY KEY CLUSTERED ([id_direccion] ASC)
GO

ALTER TABLE [metodo_pago] 
 ADD CONSTRAINT [PK_METODO_PAGO]
	PRIMARY KEY CLUSTERED ([id_metodo_pago] ASC)
GO

ALTER TABLE [orden] 
 ADD CONSTRAINT [PK_orden]
	PRIMARY KEY CLUSTERED ([id_orden] ASC)
GO

ALTER TABLE [orden_venta] 
 ADD CONSTRAINT [PK_orden_venta]
	PRIMARY KEY CLUSTERED ([id_orden] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_orden_venta_metodo_pago] 
 ON [orden_venta] ([id_metodo_pago] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_orden_venta_orden] 
 ON [orden_venta] ([id_orden] ASC)
GO

ALTER TABLE [persona] 
 ADD CONSTRAINT [PK_persona]
	PRIMARY KEY CLUSTERED ([id_persona] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_persona_direccion] 
 ON [persona] ([id_direccion] ASC)
GO

ALTER TABLE [producto] 
 ADD CONSTRAINT [PK_producto]
	PRIMARY KEY CLUSTERED ([id_producto] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_producto_categoria] 
 ON [producto] ([id_categoria] ASC)
GO

ALTER TABLE [rol] 
 ADD CONSTRAINT [PK_id_rol]
	PRIMARY KEY CLUSTERED ([id_rol] ASC)
GO

ALTER TABLE [tarjeta] 
 ADD CONSTRAINT [PK_tarjeta]
	PRIMARY KEY CLUSTERED ([id_tarjeta] ASC)
GO

ALTER TABLE [usuario] 
 ADD CONSTRAINT [PK_usuario]
	PRIMARY KEY CLUSTERED ([id_persona] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [cliente] ADD CONSTRAINT [FK_cliente_persona]
	FOREIGN KEY ([id_persona]) REFERENCES [persona] ([id_persona]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [detalle_orden] ADD CONSTRAINT [FK_id_orden]
	FOREIGN KEY ([id_orden]) REFERENCES [orden] ([id_orden]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [detalle_orden] ADD CONSTRAINT [FK_id_producto]
	FOREIGN KEY ([id_producto]) REFERENCES [producto] ([id_producto]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [orden_venta] ADD CONSTRAINT [FK_orden_venta_cliente]
	FOREIGN KEY ([id_cliente]) REFERENCES [cliente] ([id_persona]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [orden_venta] ADD CONSTRAINT [FK_orden_venta_metodo_pago]
	FOREIGN KEY ([id_metodo_pago]) REFERENCES [metodo_pago] ([id_metodo_pago]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [orden_venta] ADD CONSTRAINT [FK_orden_venta_orden]
	FOREIGN KEY ([id_orden]) REFERENCES [orden] ([id_orden]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [producto] ADD CONSTRAINT [FK_producto_categoria]
	FOREIGN KEY ([id_categoria]) REFERENCES [categoria] ([id_categoria]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [tarjeta] ADD CONSTRAINT [FK_tarjeta_orden_venta]
	FOREIGN KEY ([id_orden]) REFERENCES [orden_venta] ([id_orden]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [usuario] ADD CONSTRAINT [FK_usuario_persona]
	FOREIGN KEY ([id_persona]) REFERENCES [persona] ([id_persona]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [usuario] ADD CONSTRAINT [FK_usuario_rol]
	FOREIGN KEY ([id_rol]) REFERENCES [rol] ([id_rol]) ON DELETE No Action ON UPDATE No Action
GO
