///////////////////////////////////////////////////////////
//  Cliente.cs
//  Implementation of the Class Cliente
//  Generated by Enterprise Architect
//  Created on:      30-abr.-2021 19:48:56
//  Original author: AR00111194
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

namespace Entity
{
	public class Cliente : Persona
	{

		public Cliente()
		{

		}
	}//end Cliente
}