///////////////////////////////////////////////////////////
//  EntidadPersistible.cs
//  Implementation of the Class EntidadPersistible
//  Generated by Enterprise Architect
//  Created on:      30-abr.-2021 22:44:25
//  Original author: AR00111194
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Entidades.Entidades {
	public abstract class EntidadPersistible {

		public EntidadPersistible(){

		}

		~EntidadPersistible(){

		}

		public int ID{
			get;
			set;
		}

	}//end EntidadPersistible

}//end namespace Entidades