///////////////////////////////////////////////////////////
//  MetodoDePago.cs
//  Implementation of the Class MetodoDePago
//  Generated by Enterprise Architect
//  Created on:      30-abr.-2021 19:40:47
//  Original author: Yannick
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Entity {
    public abstract class MetodoDePago
    {
        private string _tipo;
        private int _id;

        public int ID_MetodoDePago
        {
            get { return _id; }
            set { _id = value; }
        }


        public string TipoMetodoDePago
        {
            get { return _tipo; }
            set { _tipo = value; }
        }



        public MetodoDePago()
        {

        }



    }//end MetodoDePago
}