///////////////////////////////////////////////////////////
//  OrdenDeVenta.cs
//  Implementation of the Class OrdenDeVenta
//  Generated by Enterprise Architect
//  Created on:      30-abr.-2021 19:42:04
//  Original author: AR00111194
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

namespace Entity
{ 
	public class OrdenDeVenta : Orden
	{

		private Cliente _cliente;
		private MetodoDePago _metodoDePago;

		public OrdenDeVenta()
		{

		}

		public Cliente Cliente
		{
			get;
			set;
		}

		public MetodoDePago MetodoDePago
		{
			get;
			set;
		}

	}//end OrdenDeVenta
}
