///////////////////////////////////////////////////////////
//  Orden.cs
//  Implementation of the Class Orden
//  Generated by Enterprise Architect
//  Created on:      30-abr.-2021 19:47:06
//  Original author: AR00111194
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;


namespace Entity {
	public abstract class Orden {

		private List<DetalleOrden> _detalles = new List<DetalleOrden>();
		private DateTime _fecha;
		private Usuario _usuarioCreador;
        private int _id;

        public int ID_Orden
        {
            get { return _id; }
            set { _id = value; }
        }


        public Orden(){
			this._fecha = DateTime.Now;
		}
		public Orden(List<DetalleOrden> Detalles, Usuario UsuarioCreador)
		{
			this._fecha = DateTime.Now; 
		}


		public List<DetalleOrden> Detalles{
			get;
			set;
		}

		public DateTime Fecha{
			get;
		}

		public Usuario UsuarioCreador{
			get;
			set;
		}

	}//end Orden

}//end namespace General