///////////////////////////////////////////////////////////
//  Producto.cs
//  Implementation of the Class Producto
//  Generated by Enterprise Architect
//  Created on:      30-abr.-2021 19:47:43
//  Original author: AR00111194
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Entity {
	public class Producto {

		private Categoria _categoria;
        private int _id;
		private string _nombre;
		private float _precioCompra;
		private float _precioVenta;
        private int _stock;




        public Producto(){

		}

		~Producto(){

		}

		public Categoria Categoria{
			get;
			set;
		}

        public int ID
        {
            get { return _id; }
            set { _id = value; }
        }

        public int Stock
        {
            get { return _stock; }
            set { _stock = value; }
        }

		public string Nombre{
			get;
			set;
		}

		public float PrecioCompra{
			get;
			set;
		}

		public float PrecioVenta{
			get;
			set;
		}

	}//end Producto

}//end namespace General