///////////////////////////////////////////////////////////
//  Reporte.cs
//  Implementation of the Class Reporte
//  Generated by Enterprise Architect
//  Created on:      30-abr.-2021 19:47:35
//  Original author: AR00111194
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace General {
	public abstract class Reporte {

		private DataTable _tablaReporte;

		public Reporte(){

		}

		~Reporte(){

		}

		public DataTable TablaReporte{
			get;
			set;
		}

	}//end Reporte

}//end namespace General