///////////////////////////////////////////////////////////
//  Categoria.cs
//  Implementation of the Class Categoria
//  Generated by Enterprise Architect
//  Created on:      30-abr.-2021 19:47:15
//  Original author: AR00111194
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace General {
	public class Categoria {

		private string _nombre;

		public Categoria(){

		}

		public string Nombre{
			get;
			set;
		}

	}//end Categoria

}//end namespace General