///////////////////////////////////////////////////////////
//  MetodoDePago.cs
//  Implementation of the Class MetodoDePago
//  Generated by Enterprise Architect
//  Created on:      30-abr.-2021 19:40:47
//  Original author: Yannick
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public abstract class MetodoDePago {

    public MetodoDePago()
    {

    }

    public virtual bool Validar()
    {
        return false;
    }



}//end MetodoDePago