///////////////////////////////////////////////////////////
//  Producto.cs
//  Implementation of the Class Producto
//  Generated by Enterprise Architect
//  Created on:      30-abr.-2021 19:47:43
//  Original author: AR00111194
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using General;
namespace General {
	public class Producto {

		private Categoria _categoria;
		private string _nombre;
		private float _precioCompra;
		private float _precioVenta;

		public Producto(){

		}

		~Producto(){

		}

		public Categoria Categoria{
			get;
			set;
		}

		public string Nombre{
			get;
			set;
		}

		public float PrecioCompra{
			get;
			set;
		}

		public float PrecioVenta{
			get;
			set;
		}

	}//end Producto

}//end namespace General