///////////////////////////////////////////////////////////
//  Rol.cs
//  Implementation of the Class Rol
//  Generated by Enterprise Architect
//  Created on:      01-may.-2021 22:57:03
//  Original author: AR00111194
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Entidades.Entidades;
namespace Entidades.Entidades {
	public class Rol : EntidadPersistible {

		private string _descripcion;
		private List<Permiso> _permisos = new List<Permiso>();

		public Rol(){

		}

		~Rol(){

		}

		public string Descripcion{
			get;
			set;
		}

		public List<Permiso> Permisos{
			get;
			set;
		}

	}//end Rol

}//end namespace Entidades