///////////////////////////////////////////////////////////
//  Efectivo.cs
//  Implementation of the Class Efectivo
//  Generated by Enterprise Architect
//  Created on:      30-abr.-2021 19:42:29
//  Original author: AR00111194
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace ENTITY
{
	public class Efectivo : MetodoDePago
	{

		public Efectivo()
		{

		}

	}//end Efectivo
}