///////////////////////////////////////////////////////////
//  EntidadPersistible.cs
//  Implementation of the Class EntidadPersistible
//  Generated by Enterprise Architect
//  Created on:      01-may.-2021 22:58:41
//  Original author: AR00111194
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace ENTITY
{
	public abstract class EntidadPersistible {
        private int _id;

        public int ID
        {
            get { return _id; }
            set { _id = value; }
        }

        public EntidadPersistible(){

		}

	}//end EntidadPersistible

}//end namespace Entidades