///////////////////////////////////////////////////////////
//  MetodoDePago.cs
//  Implementation of the Class MetodoDePago
//  Generated by Enterprise Architect
//  Created on:      30-abr.-2021 19:40:47
//  Original author: Yannick
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace ENTITY
{
    public abstract class MetodoDePago : EntidadPersistible
    {
        private string _tipo;

        public string TipoMetodoDePago
        {
            get { return _tipo; }
            set { _tipo = value; }
        }



        public MetodoDePago()
        {

        }



    }//end MetodoDePago
}