///////////////////////////////////////////////////////////
//  Permiso.cs
//  Implementation of the Class Permiso
//  Generated by Enterprise Architect
//  Created on:      01-may.-2021 22:56:54
//  Original author: AR00111194
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;




namespace ENTITY
{
	public class Permiso : EntidadPersistible {

		private string _descripcion;

		public Permiso(){

		}

		public string Descripcion{
			get;
			set;
		}

	}//end Permiso

}//end namespace Entity