///////////////////////////////////////////////////////////
//  Usuario.cs
//  Implementation of the Class Usuario
//  Generated by Enterprise Architect
//  Created on:      01-may.-2021 19:13:41
//  Original author: AR00111194
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

namespace ENTITY
{
	public class Usuario : Persona {

		private int _legajo;
		private Rol _rol;

		public Usuario(){

		}

		~Usuario(){

		}

		public int Legajo{
			get;
			set;
		}

		public Rol Rol{
			get;
			set;
		}

	}//end Usuario

}//end namespace Entidades